name: cs224n-project-env
channels:
  - pytorch
  - defaults
dependencies:
  - huggingface_hub
  - datasets
  - transformers
  - python=3.9
  - pytorch
  - numpy
  - scipy
  - tqdm
  - docopt
  - nltk
  - torchvision
  - torchaudio
  - pip
  - ipykernel
  - ipywidgets
  - pip:
    - sentencepiece
    - lxml==5.0.0
    - sacrebleu
    - tensorboard